#!/bin/bash

cat <<EOF

Serendipity $(grep versionInstalled /var/www/html/serendipity_config_local.inc.php | sed 's#.*'\''\(.*\)'\'';#\1#') is installed in /var/www/html.

To continue the installation, open http://$(/usr/local/bin/oc-metadata PUBLIC_IP_ADDRESS)/ in your browser.

Serendipity will detect SQLite as database, no settings must be changed.

You can hide this message on the next connection by deleting the $0 file.

EOF
